In [11]:
import pandas as pd
import numpy as np

#data cleaning
df = pd.read_csv('https://raw.githubusercontent.com/veghmark12/r_d_investments/refs/heads/main/df_with_closest_fua_extended_2023.csv')

In [13]:
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('angel_fund', 'angel', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('corporate_venture_fund', 'venture_capital', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('sovereign_wealth_fund', 'venture_capital', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('incubator', 'accelerator&incubator', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('accelerator', 'accelerator&incubator', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('accelerator&incubator&incubator', 'accelerator&incubator', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace(['venture_capital','angel','private_equity','family_office','corporate','investment fund'], 'investment entities', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace(['accelerator&incubator','workspace','workspace location'], 'support programs', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('support programs location', 'support programs', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace(['government','crowdfunding','non-profit'], 'public and non-profit', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('public and non-profi', 'public and non-profit', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('public and public and non-profitt', 'public and non-profit', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('public and non-profitt', 'public and non-profit', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('public and non-profit & public and non-profit', 'public and non-profit', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace(['advisor','service provider'], 'advisory and service provider', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('advisory and advisory and service provider', 'advisory and service provider', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('company', 'investment entities', regex=True)
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].replace('university', 'public and non-profit', regex=True)

In [14]:
# Extract the values from the column into a list
values_list = df['EACH INVESTOR TYPES'].tolist()

In [15]:
# Ensure all entries are strings; replace None or NaN with an empty string
cleaned_list = [str(item) if item is not None else '' for item in values_list]

# Split the values by both semicolons and commas, and flatten the result
separated_list = [item for sublist in cleaned_list for item in sublist.replace(';', ',').split(',')]

# Get unique values
real_unique_values = pd.Series(separated_list).unique()

# Output unique values
print(real_unique_values)

df

['investment entities' 'public and non-profit' 'support programs'
 'advisory and service provider' 'nan' 'user']

,NAME,TAGLINE,HQ REGION,HQ COUNTRY,HQ CITY kész,LATITUDE,LONGITUDE,TOTAL FUNDING (EUR M) kész,TAGS,INDUSTRIES,SUB INDUSTRIES,GROWTH STAGE,INVESTORS,EACH INVESTOR TYPES,Closest FUA
0,Cylib,Battery recycling with proprietary end-to-end ...,Europe,Germany,Aachen,50.776351,6.083862,11.60,lithium ion batteries;recycling;circular econo...,energy,waste solution;energy storage,early growth,Speedinvest;Vsquared Ventures;Lawrence Leuschn...,investment entities;investment entities;invest...,Aachen
1,Accure,"Improving the safety, reliability and longevit...",Europe,Germany,Aachen,50.779634,6.100500,9.57,sustainable development goals;climate tech;bat...,energy,energy efficiency;energy storage,late growth,Capnamic Ventures;42CAP;Blue Bear Capital;MK V...,investment entities;investment entities;invest...,Aachen
2,VOLTFANG,Develops home storage solutions for private ho...,Europe,Germany,Aachen,50.779563,6.082269,1.10,spinout;sustainable development goals,energy,energy storage,early growth,Antonio Mesquida Küsters;Keith Sauvant;RWTH Aa...,investment entities;investment entities;public...,Aachen
3,Ion Kraft,Plasma technology for recyclable barrier plast...,Europe,Germany,Aachen,50.787009,6.048905,2.50,recycling;biotechnology;sustainable developmen...,energy,waste solution,seed,European Innovation Council,public and non-profit,Aachen
4,Liftra,Development and manufacturing of specialized l...,Europe,Denmark,Aalborg,57.009972,9.900337,1.94,wind energy;sustainable development goals;clim...,energy;transportation,clean energy;logistics & delivery,late growth,European Innovation Council;Market Maturation ...,public and non-profit;investment entities,Aalborg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,SOLATOM,Develops solar boilers for the generation of h...,Europe,Spain,Valencia,39.461461,-0.329891,1.69,NaN,energy,oil & gas;water;clean energy,seed,Katapult;Ship2B Foundation;Enagás Emprende;EIT...,support programs;investment entities;investmen...,Valencia
943,Gana Energía,Offering a real alternative to the oligopoly o...,Europe,Spain,Valencia,39.467571,-0.390784,1.45,NaN,energy,energy providers;clean energy,early growth,Bewater Funds;Angels Capital;Repsol;François D...,investment entities;investment entities;invest...,Valencia
944,oekostrom AG,A producer and supplier of electricity from re...,Europe,Austria,Vienna,48.184282,16.372678,12.58,NaN,energy,oil & gas;clean energy,early growth,FSP Ventures,investment entities,Vienna
945,Magallanes Renovables,"A renewable energy (tidal) company, focused on...",Europe,Spain,Vigo,42.280422,-8.609624,1.05,research and development,energy,clean energy,early growth,Horizon 2020 FTI (Fast Track to Innovation),public and non-profit,Porto
946,Circu Li-ion,Fighting the climate crisis by maximising the ...,Europe,Luxembourg,Luxembourg,49.562410,6.148563,2.53,NaN,energy,waste solution;energy storage,early growth,European Innovation Council;EIC Fund (European...,public and non-profit;investment entities;inve...,Luxembourg

In [16]:
# Extract the values from the column into a list
values_list = df['EACH INVESTOR TYPES'].tolist()

values_list

['investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;support programs',
 'investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit',
 'public and non-profit;investment entities',
 'investment entities',
 'public and non-profit;public and non-profit',
 'public and non-profit;public and non-profit',
 'investment entities;investment entities;investment entities',
 'public and non-profit;investment entities;support programs',
 'public and non-profit;public and non-profit;public and non-profit',
 'investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit',
 'investment entities;support programs;investment entities',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities',
 'public and non-profit',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit',
 'investment entities;investment entities',
 'public and non-profit',
 'investment entities,investment entities',
 'advisory and service provider,support programs;investment entities;support programs',
 'investment entities;investment entities;support programs;investment entities,investment entities;support programs;investment entities',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;public and non-profit',
 'public and non-profit;investment entities;public and non-profit;investment entities',
 'support programs;support programs',
 'public and non-profit',
 'investment entities,investment entities;investment entities',
 'investment entities;investment entities;advisory and service provider;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;public and non-profit;public and non-profit;investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities,investment entities,investment entities;investment entities,investment entities;advisory and service provider,investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit;investment entities;investment entities',
 'support programs;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;investment entities;support programs;support programs;investment entities;investment entities;public and non-profit;investment entities;public and non-profit',
 'investment entities',
 'investment entities;investment entities',
 'investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities;support programs;support programs;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities,investment entities',
 'investment entities;support programs',
 'support programs;investment entities;investment entities;investment entities',
 'investment entities;investment entities,investment entities;investment entities;support programs;investment entities,investment entities;support programs;support programs;investment entities;investment entities,investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities,investment entities',
 'investment entities;investment entities;public and non-profit;public and non-profit',
 'public and non-profit;investment entities;investment entities;support programs',
 'investment entities;support programs;investment entities;support programs;investment entities;support programs;investment entities;investment entities;support programs;support programs;support programs',
 'public and non-profit;investment entities;public and non-profit;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;public and non-profit;investment entities;investment entities;support programs',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities,investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;public and non-profit',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;advisory and service provider,investment entities;public and non-profit',
 'investment entities;investment entities;support programs',
 'public and non-profit;investment entities;support programs;support programs',
 'public and non-profit',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;support programs;investment entities;investment entities',
 'support programs;public and non-profit;public and non-profit;investment entities;support programs',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities',
 'public and non-profit;investment entities;investment entities;investment entities;public and non-profit',
 'investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;support programs',
 'investment entities;public and non-profit;public and non-profit;public and non-profit;public and non-profit',
 'investment entities;investment entities;advisory and service provider;investment entities;support programs;support programs',
 'investment entities',
 'public and non-profit;public and non-profit',
 'public and non-profit;public and non-profit;investment entities;investment entities,investment entities;public and non-profit',
 'public and non-profit',
 'support programs;public and non-profit;investment entities;investment entities;investment entities',
 'investment entities,investment entities;investment entities',
 'support programs;investment entities;public and non-profit;public and non-profit;investment entities;investment entities;support programs;public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit;investment entities;investment entities;support programs;investment entities;investment entities;investment entities;investment entities;investment entities;public and non-profit;support programs',
 'support programs;investment entities;investment entities;investment entities;support programs;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;support programs;investment entities',
 'public and non-profit;public and non-profit',
 'investment entities;public and non-profit;public and non-profit;investment entities;investment entities',
 'investment entities;public and non-profit;public and non-profit;public and non-profit;public and non-profit',
 'public and non-profit;investment entities,investment entities;investment entities;investment entities;investment entities',
 'investment entities;public and non-profit;investment entities,investment entities;investment entities;public and non-profit;support programs;investment entities;public and non-profit;public and non-profit;public and non-profit;support programs;investment entities',
 'investment entities;investment entities;support programs;support programs;investment entities;investment entities;investment entities',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;public and non-profit;investment entities;investment entities;public and non-profit;public and non-profit',
 'public and non-profit;support programs',
 'investment entities;support programs;investment entities;public and non-profit;investment entities;investment entities',
 'support programs;support programs',
 'investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;support programs;support programs',
 'public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;support programs;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities',
 'support programs;support programs',
 'investment entities;public and non-profit;support programs',
 'investment entities;public and non-profit;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;support programs',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;advisory and service provider;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'support programs;support programs;support programs;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;support programs;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities,investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;support programs;support programs',
 'investment entities;support programs;support programs;support programs;investment entities;investment entities',
 'investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;support programs;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'support programs;investment entities;advisory and service provider;investment entities;support programs;advisory and service provider,investment entities',
 'investment entities;investment entities,investment entities;investment entities;investment entities;support programs;support programs;support programs;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;support programs;public and non-profit;support programs;investment entities;investment entities;public and non-profit;support programs;support programs;public and non-profit;investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;public and non-profit;support programs',
 'investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit;support programs;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;support programs;investment entities;support programs',
 'public and non-profit;public and non-profit;investment entities,investment entities;investment entities;investment entities;investment entities,investment entities;investment entities',
 'investment entities;investment entities;investment entities;support programs;investment entities',
 'investment entities;investment entities;investment entities',
 'investment entities;public and non-profit',
 'investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs;public and non-profit;investment entities',
 nan,
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;support programs;investment entities;investment entities',
 'investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;support programs',
 'investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities',
 'investment entities;support programs;investment entities;investment entities;investment entities;investment entities;support programs;support programs;investment entities',
 'public and non-profit;investment entities',
 'investment entities;support programs;investment entities',
 'investment entities;investment entities,investment entities;investment entities',
 'investment entities;investment entities,investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities,investment entities;investment entities;support programs',
 'public and non-profit;support programs;public and non-profit;support programs;support programs;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'support programs;investment entities;public and non-profit;support programs;support programs;investment entities;support programs;public and non-profit;public and non-profit;investment entities;investment entities;investment entities;investment entities',
 'investment entities',
 'public and non-profit',
 'investment entities;public and non-profit;investment entities;investment entities;investment entities;investment entities;investment entities;investment entities',
 'public and non-profit;investment entities',
 'public and non-profit;investment entities;investment entities,investment entities;investment entities;investment entities;investment entities,investment entities;investment entities',
 'investment entities;investment entities;investment entities;investment entities',
 'investment entities;investment entities;investment entities;support programs;investment entities',

In [17]:
import pandas as pd

# Ensure all values in the column are strings and replace NaN with an empty string
df['EACH INVESTOR TYPES'] = df['EACH INVESTOR TYPES'].fillna('').astype(str)

# Categories to count
categories = ['public and non-profit', 'investment entities', 'support programs','advisory and service provider']

# Count occurrences of each category
for category in categories:
    df[category] = df['EACH INVESTOR TYPES'].apply(lambda x: x.split(';').count(category))

df

,NAME,TAGLINE,HQ REGION,HQ COUNTRY,HQ CITY kész,LATITUDE,LONGITUDE,TOTAL FUNDING (EUR M) kész,TAGS,INDUSTRIES,SUB INDUSTRIES,GROWTH STAGE,INVESTORS,EACH INVESTOR TYPES,Closest FUA,public and non-profit,investment entities,support programs,advisory and service provider
0,Cylib,Battery recycling with proprietary end-to-end ...,Europe,Germany,Aachen,50.776351,6.083862,11.60,lithium ion batteries;recycling;circular econo...,energy,waste solution;energy storage,early growth,Speedinvest;Vsquared Ventures;Lawrence Leuschn...,investment entities;investment entities;invest...,Aachen,1,11,0,0
1,Accure,"Improving the safety, reliability and longevit...",Europe,Germany,Aachen,50.779634,6.100500,9.57,sustainable development goals;climate tech;bat...,energy,energy efficiency;energy storage,late growth,Capnamic Ventures;42CAP;Blue Bear Capital;MK V...,investment entities;investment entities;invest...,Aachen,0,5,1,0
2,VOLTFANG,Develops home storage solutions for private ho...,Europe,Germany,Aachen,50.779563,6.082269,1.10,spinout;sustainable development goals,energy,energy storage,early growth,Antonio Mesquida Küsters;Keith Sauvant;RWTH Aa...,investment entities;investment entities;public...,Aachen,1,7,0,0
3,Ion Kraft,Plasma technology for recyclable barrier plast...,Europe,Germany,Aachen,50.787009,6.048905,2.50,recycling;biotechnology;sustainable developmen...,energy,waste solution,seed,European Innovation Council,public and non-profit,Aachen,1,0,0,0
4,Liftra,Development and manufacturing of specialized l...,Europe,Denmark,Aalborg,57.009972,9.900337,1.94,wind energy;sustainable development goals;clim...,energy;transportation,clean energy;logistics & delivery,late growth,European Innovation Council;Market Maturation ...,public and non-profit;investment entities,Aalborg,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,SOLATOM,Develops solar boilers for the generation of h...,Europe,Spain,Valencia,39.461461,-0.329891,1.69,NaN,energy,oil & gas;water;clean energy,seed,Katapult;Ship2B Foundation;Enagás Emprende;EIT...,support programs;investment entities;investmen...,Valencia,0,3,3,0
943,Gana Energía,Offering a real alternative to the oligopoly o...,Europe,Spain,Valencia,39.467571,-0.390784,1.45,NaN,energy,energy providers;clean energy,early growth,Bewater Funds;Angels Capital;Repsol;François D...,investment entities;investment entities;invest...,Valencia,0,4,0,0
944,oekostrom AG,A producer and supplier of electricity from re...,Europe,Austria,Vienna,48.184282,16.372678,12.58,NaN,energy,oil & gas;clean energy,early growth,FSP Ventures,investment entities,Vienna,0,1,0,0
945,Magallanes Renovables,"A renewable energy (tidal) company, focused on...",Europe,Spain,Vigo,42.280422,-8.609624,1.05,research and development,energy,clean energy,early growth,Horizon 2020 FTI (Fast Track to Innovation),public and non-profit,Porto,1,0,0,0
946,Circu Li-ion,Fighting the climate crisis by maximising the ...,Europe,Luxembourg,Luxembourg,49.562410,6.148563,2.53,NaN,energy,waste solution;energy storage,early growth,European Innovation Council;EIC Fund (European...,public and non-profit;investment entities;inve...,Luxembourg,3,2,1,0

In [18]:
# Save the updated dataframe to a new file
output_file = 'df_with_closest_fua_investorclusters.csv'
df.to_csv(output_file, index=False)